

export const LOAD_CAR_SUCCESS = 'LOAD_CAR_SUCCESS';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';